# NeON build file (http://github.com/c4s4/neon)

extends: slides
default: [clean, slides]

properties:
  TITLE:   "L'Ordinateur Quantique, Mythe ou Réalité ?"
  OPTIONS: '{ratio: "4:3"}'
  #OPTIONS: '{ratio: "16:9"}'
